version: "3.8"

services:

  app:
    build:
      context: docker
    container_name: here-distance-calculator
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "4005:80"